### PR TITLE
moabrsv module, autoconf/ltdl cleanup

### PR DESCRIPTION
**Pull request by tabaer**
This pull request does three things:
1. Add a module to pull host lists from Moab reservations.  (This was the original point of the exercise, which required the other two items.)
2. Remove files generated by the bootstrap process (configure, */Makefile.in, etc.).
3. Remove the ancient version of ltdl used and instead call dlopen and friends directly.  (Not all of the libtool machinery is removed, just enough to make things work.)

### CODE REVIEW

**Comment by grondo** [comment]
Awesome, thanks!!

I'm going to check this out today. However, I think for sanity's sake, it might be best to split this into two PRs. The first PR would contain the autotools/libtool/libltdl updates, removal of generated files, etc. -- and the second would add your new moabsrv module.

If that isn't too much trouble, I think it would be best to merge in two chunks.

Once the first PR is merged, I'm going to look at adding automated testing via travis-ci.org for pdsh. 

This represents a lot of work and I thank you for it!

**Comment by tabaer** [comment]
That sounds reasonable, assuming I can figure out how to do it.  I'll talk to a coworker whose Git Fu is stronger than mine about how to separate the two out.

**Comment by grondo** [comment]
Thanks for the understanding. I think you'll find that git makes it easy. I make heavy use of `git cherry-pick` and `git rebase --interactive`

**Comment by grondo** [comment]
With the switch from libltdl to straight dlopen(), pdsh can't open `.la` files anymore. Since the `.so` modules are built under the `.libs` directory, this path needs to be used as the fq path for the build-tree version of the pdsh binary. That is, for anything to work in the build tree, I needed the following quick patch:

```diff
diff --git a/src/pdsh/Makefile.am b/src/pdsh/Makefile.am
index cc6c4d5..f34187f 100644
--- a/src/pdsh/Makefile.am
+++ b/src/pdsh/Makefile.am
@@ -60,7 +60,7 @@ config.c: $(top_srcdir)/META $(top_builddir)/config.h
 
 testconfig.c: $(top_srcdir)/META $(top_builddir)/config.h
        @(echo "char *pdsh_version = \"$(PDSH_VERSION_FULL)\";";\
-          moddir=`cd $(top_builddir)/src/modules && pwd`; \
+          moddir=`cd $(top_builddir)/src/modules/.libs && pwd`; \
           echo "char *pdsh_module_dir = \"$$moddir\";"\
          )> testconfig.c

```

A similar change will be necessary somewhere in the tests directory, in order to pick up all the "test" modules.

**Comment by tabaer** [comment]
I'm submitted the autoconf/LTDL push request and will hold off on the moabrsv pull request till that's merged.

**Comment by grondo** [comment]
You could still open the moabsrv module PR (just base it off your autotools branch), so that others can review and comment on it.

**Pull request closed without merging**
